import type {
  Contact,
  Lead,
  Deal,
  Ticket,
  Task,
  CalendarEvent,
  User,
  Notification,
  AIInsight,
  DashboardStats,
  TicketMessage,
  Activity,
} from './types'

// Current User
export const currentUser: User = {
  id: 'user-1',
  name: 'Alex Johnson',
  email: 'alex.johnson@crmpro.com',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
  role: 'admin',
}

// Team Members
export const teamMembers: User[] = [
  currentUser,
  {
    id: 'user-2',
    name: 'Sarah Williams',
    email: 'sarah.williams@crmpro.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    role: 'sales',
  },
  {
    id: 'user-3',
    name: 'Michael Chen',
    email: 'michael.chen@crmpro.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
    role: 'sales',
  },
  {
    id: 'user-4',
    name: 'Emily Brown',
    email: 'emily.brown@crmpro.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
    role: 'support',
  },
  {
    id: 'user-5',
    name: 'David Kumar',
    email: 'david.kumar@crmpro.com',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    role: 'manager',
  },
]

// Contacts
export const contacts: Contact[] = [
  {
    id: 'contact-1',
    firstName: 'John',
    lastName: 'Smith',
    email: 'john.smith@techcorp.com',
    phone: '+1 (555) 123-4567',
    company: 'TechCorp Solutions',
    position: 'CTO',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    tags: ['enterprise', 'tech', 'decision-maker'],
    notes: 'Met at TechConf 2024. Very interested in our enterprise solution.',
    createdAt: '2024-01-15T10:30:00Z',
    lastContactedAt: '2024-03-08T14:00:00Z',
    status: 'active',
  },
  {
    id: 'contact-2',
    firstName: 'Emma',
    lastName: 'Wilson',
    email: 'emma.wilson@globalinc.com',
    phone: '+1 (555) 234-5678',
    company: 'Global Inc',
    position: 'VP of Operations',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    tags: ['enterprise', 'operations'],
    notes: 'Referred by John Smith. Looking for process automation.',
    createdAt: '2024-02-01T09:15:00Z',
    lastContactedAt: '2024-03-10T11:30:00Z',
    status: 'active',
  },
  {
    id: 'contact-3',
    firstName: 'Robert',
    lastName: 'Garcia',
    email: 'robert.garcia@startupxyz.io',
    phone: '+1 (555) 345-6789',
    company: 'StartupXYZ',
    position: 'CEO',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Robert',
    tags: ['startup', 'tech', 'founder'],
    notes: 'Fast-growing startup. Budget approval pending.',
    createdAt: '2024-02-10T16:45:00Z',
    lastContactedAt: '2024-03-05T09:00:00Z',
    status: 'active',
  },
  {
    id: 'contact-4',
    firstName: 'Lisa',
    lastName: 'Anderson',
    email: 'lisa.anderson@retailmax.com',
    phone: '+1 (555) 456-7890',
    company: 'RetailMax',
    position: 'Director of Sales',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
    tags: ['retail', 'sales'],
    notes: 'Interested in CRM migration from competitor.',
    createdAt: '2024-01-20T13:00:00Z',
    lastContactedAt: '2024-03-09T15:30:00Z',
    status: 'active',
  },
  {
    id: 'contact-5',
    firstName: 'James',
    lastName: 'Taylor',
    email: 'james.taylor@financeplus.com',
    phone: '+1 (555) 567-8901',
    company: 'FinancePlus',
    position: 'CFO',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    tags: ['finance', 'enterprise', 'decision-maker'],
    notes: 'Strict compliance requirements. Need security documentation.',
    createdAt: '2024-02-05T08:30:00Z',
    lastContactedAt: '2024-03-07T10:00:00Z',
    status: 'active',
  },
  {
    id: 'contact-6',
    firstName: 'Maria',
    lastName: 'Rodriguez',
    email: 'maria.rodriguez@healthcare.org',
    phone: '+1 (555) 678-9012',
    company: 'HealthCare Solutions',
    position: 'Operations Manager',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
    tags: ['healthcare', 'operations'],
    notes: 'HIPAA compliance is a must. Schedule demo with legal team.',
    createdAt: '2024-02-15T11:00:00Z',
    lastContactedAt: '2024-03-06T16:00:00Z',
    status: 'active',
  },
  {
    id: 'contact-7',
    firstName: 'Kevin',
    lastName: 'Lee',
    email: 'kevin.lee@mediaco.tv',
    phone: '+1 (555) 789-0123',
    company: 'MediaCo Entertainment',
    position: 'Head of Partnerships',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kevin',
    tags: ['media', 'enterprise'],
    notes: 'Looking for integration with existing tools.',
    createdAt: '2024-01-25T14:30:00Z',
    lastContactedAt: '2024-03-04T12:00:00Z',
    status: 'active',
  },
  {
    id: 'contact-8',
    firstName: 'Patricia',
    lastName: 'Moore',
    email: 'patricia.moore@edulearn.edu',
    phone: '+1 (555) 890-1234',
    company: 'EduLearn Institute',
    position: 'Administrative Director',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Patricia',
    tags: ['education', 'non-profit'],
    notes: 'Non-profit pricing requested. Decision by end of quarter.',
    createdAt: '2024-02-20T10:00:00Z',
    lastContactedAt: '2024-03-03T14:30:00Z',
    status: 'inactive',
  },
]

// Leads
export const leads: Lead[] = [
  {
    id: 'lead-1',
    name: 'Sophie Chen',
    email: 'sophie.chen@innovateai.com',
    phone: '+1 (555) 111-2222',
    company: 'InnovateAI',
    source: 'linkedin',
    status: 'qualified',
    score: 92,
    assignedTo: 'user-2',
    notes: 'High potential. AI startup with recent Series B funding.',
    createdAt: '2024-03-01T09:00:00Z',
    lastActivityAt: '2024-03-10T15:00:00Z',
  },
  {
    id: 'lead-2',
    name: 'Marcus Johnson',
    email: 'marcus.j@buildright.com',
    phone: '+1 (555) 222-3333',
    company: 'BuildRight Construction',
    source: 'website',
    status: 'contacted',
    score: 78,
    assignedTo: 'user-3',
    notes: 'Filled out contact form. Interested in project management features.',
    createdAt: '2024-03-05T11:30:00Z',
    lastActivityAt: '2024-03-09T10:00:00Z',
  },
  {
    id: 'lead-3',
    name: 'Amanda Foster',
    email: 'afoster@cloudserve.io',
    phone: '+1 (555) 333-4444',
    company: 'CloudServe',
    source: 'referral',
    status: 'new',
    score: 85,
    assignedTo: 'user-2',
    notes: 'Referred by existing customer TechCorp. Hot lead!',
    createdAt: '2024-03-08T14:00:00Z',
    lastActivityAt: '2024-03-08T14:00:00Z',
  },
  {
    id: 'lead-4',
    name: 'David Park',
    email: 'dpark@logisticsco.com',
    phone: '+1 (555) 444-5555',
    company: 'LogisticsCo',
    source: 'event',
    status: 'qualified',
    score: 71,
    assignedTo: 'user-3',
    notes: 'Met at Supply Chain Summit. Enterprise requirements.',
    createdAt: '2024-02-28T16:00:00Z',
    lastActivityAt: '2024-03-07T11:30:00Z',
  },
  {
    id: 'lead-5',
    name: 'Jennifer White',
    email: 'jwhite@creativestudio.com',
    phone: '+1 (555) 555-6666',
    company: 'Creative Studio',
    source: 'cold-call',
    status: 'contacted',
    score: 45,
    assignedTo: 'user-2',
    notes: 'Small agency. Limited budget but growing fast.',
    createdAt: '2024-03-02T10:00:00Z',
    lastActivityAt: '2024-03-06T09:00:00Z',
  },
  {
    id: 'lead-6',
    name: 'Richard Brown',
    email: 'rbrown@manufacturing.com',
    phone: '+1 (555) 666-7777',
    company: 'Manufacturing Plus',
    source: 'website',
    status: 'unqualified',
    score: 25,
    assignedTo: 'user-3',
    notes: 'Looking for ERP, not CRM. Redirected to partners.',
    createdAt: '2024-03-04T13:00:00Z',
    lastActivityAt: '2024-03-05T08:00:00Z',
  },
  {
    id: 'lead-7',
    name: 'Nancy Davis',
    email: 'ndavis@lawfirm.com',
    phone: '+1 (555) 777-8888',
    company: 'Davis & Associates Law',
    source: 'referral',
    status: 'new',
    score: 88,
    assignedTo: 'user-2',
    notes: 'Law firm looking for client management solution.',
    createdAt: '2024-03-09T09:30:00Z',
    lastActivityAt: '2024-03-09T09:30:00Z',
  },
  {
    id: 'lead-8',
    name: 'Thomas Miller',
    email: 'tmiller@realestate.com',
    phone: '+1 (555) 888-9999',
    company: 'Prime Real Estate',
    source: 'linkedin',
    status: 'contacted',
    score: 67,
    assignedTo: 'user-3',
    notes: 'Real estate agency. Needs mobile app access.',
    createdAt: '2024-03-03T15:00:00Z',
    lastActivityAt: '2024-03-08T12:00:00Z',
  },
]

// Activities for deals
const activities: Activity[] = [
  {
    id: 'activity-1',
    type: 'call',
    title: 'Discovery Call',
    description: 'Initial call to understand requirements',
    date: '2024-03-08T10:00:00Z',
    completed: true,
    relatedTo: { type: 'deal', id: 'deal-1' },
    createdBy: 'user-1',
  },
  {
    id: 'activity-2',
    type: 'meeting',
    title: 'Product Demo',
    description: 'Full product demonstration with stakeholders',
    date: '2024-03-12T14:00:00Z',
    completed: false,
    relatedTo: { type: 'deal', id: 'deal-1' },
    createdBy: 'user-2',
  },
]

// Deals
export const deals: Deal[] = [
  {
    id: 'deal-1',
    title: 'TechCorp Enterprise License',
    value: 150000,
    currency: 'USD',
    stage: 'negotiation',
    probability: 75,
    contactId: 'contact-1',
    contact: contacts[0],
    expectedCloseDate: '2024-03-31T00:00:00Z',
    notes: 'Enterprise deal. Negotiating on price and implementation timeline.',
    activities: activities,
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-03-10T16:00:00Z',
  },
  {
    id: 'deal-2',
    title: 'Global Inc Process Automation',
    value: 85000,
    currency: 'USD',
    stage: 'proposal',
    probability: 60,
    contactId: 'contact-2',
    contact: contacts[1],
    expectedCloseDate: '2024-04-15T00:00:00Z',
    notes: 'Proposal sent. Awaiting feedback from operations team.',
    activities: [],
    createdAt: '2024-02-05T11:00:00Z',
    updatedAt: '2024-03-09T14:00:00Z',
  },
  {
    id: 'deal-3',
    title: 'StartupXYZ Growth Plan',
    value: 24000,
    currency: 'USD',
    stage: 'qualified',
    probability: 40,
    contactId: 'contact-3',
    contact: contacts[2],
    expectedCloseDate: '2024-04-30T00:00:00Z',
    notes: 'Startup with limited budget. Interested in growth plan.',
    activities: [],
    createdAt: '2024-02-15T09:00:00Z',
    updatedAt: '2024-03-08T10:00:00Z',
  },
  {
    id: 'deal-4',
    title: 'RetailMax CRM Migration',
    value: 120000,
    currency: 'USD',
    stage: 'proposal',
    probability: 55,
    contactId: 'contact-4',
    contact: contacts[3],
    expectedCloseDate: '2024-05-01T00:00:00Z',
    notes: 'Migration from competitor. Need detailed transition plan.',
    activities: [],
    createdAt: '2024-02-01T14:00:00Z',
    updatedAt: '2024-03-10T11:00:00Z',
  },
  {
    id: 'deal-5',
    title: 'FinancePlus Compliance Package',
    value: 200000,
    currency: 'USD',
    stage: 'negotiation',
    probability: 80,
    contactId: 'contact-5',
    contact: contacts[4],
    expectedCloseDate: '2024-03-25T00:00:00Z',
    notes: 'High-value deal. Security audit completed. Final pricing discussion.',
    activities: [],
    createdAt: '2024-02-10T10:00:00Z',
    updatedAt: '2024-03-10T15:00:00Z',
  },
  {
    id: 'deal-6',
    title: 'HealthCare Solutions Annual',
    value: 75000,
    currency: 'USD',
    stage: 'lead',
    probability: 20,
    contactId: 'contact-6',
    contact: contacts[5],
    expectedCloseDate: '2024-06-30T00:00:00Z',
    notes: 'Early stage. HIPAA compliance documentation being prepared.',
    activities: [],
    createdAt: '2024-02-20T13:00:00Z',
    updatedAt: '2024-03-06T09:00:00Z',
  },
  {
    id: 'deal-7',
    title: 'MediaCo Integration Suite',
    value: 95000,
    currency: 'USD',
    stage: 'qualified',
    probability: 45,
    contactId: 'contact-7',
    contact: contacts[6],
    expectedCloseDate: '2024-05-15T00:00:00Z',
    notes: 'Requires custom integrations. Technical assessment ongoing.',
    activities: [],
    createdAt: '2024-02-25T15:00:00Z',
    updatedAt: '2024-03-05T16:00:00Z',
  },
  {
    id: 'deal-8',
    title: 'EduLearn Non-Profit License',
    value: 35000,
    currency: 'USD',
    stage: 'closed-won',
    probability: 100,
    contactId: 'contact-8',
    contact: contacts[7],
    expectedCloseDate: '2024-03-01T00:00:00Z',
    actualCloseDate: '2024-03-01T00:00:00Z',
    notes: 'Non-profit deal closed with special pricing.',
    activities: [],
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-03-01T12:00:00Z',
  },
  {
    id: 'deal-9',
    title: 'TechStart Pilot Program',
    value: 12000,
    currency: 'USD',
    stage: 'closed-lost',
    probability: 0,
    contactId: 'contact-3',
    contact: contacts[2],
    expectedCloseDate: '2024-02-15T00:00:00Z',
    actualCloseDate: '2024-02-20T00:00:00Z',
    notes: 'Lost to competitor. Price was the main factor.',
    activities: [],
    createdAt: '2024-01-05T09:00:00Z',
    updatedAt: '2024-02-20T10:00:00Z',
  },
]

// Ticket Messages
const ticketMessages: TicketMessage[] = [
  {
    id: 'msg-1',
    content: 'I am unable to access my dashboard since yesterday. It shows a blank screen.',
    sender: 'customer',
    senderName: 'John Smith',
    createdAt: '2024-03-09T10:00:00Z',
  },
  {
    id: 'msg-2',
    content: 'Thank you for reaching out. Can you please clear your browser cache and try again?',
    sender: 'agent',
    senderName: 'Emily Brown',
    createdAt: '2024-03-09T10:30:00Z',
  },
  {
    id: 'msg-3',
    content: 'I tried that but the issue persists. I am using Chrome on Windows.',
    sender: 'customer',
    senderName: 'John Smith',
    createdAt: '2024-03-09T11:00:00Z',
  },
]

// Tickets
export const tickets: Ticket[] = [
  {
    id: 'ticket-1',
    subject: 'Dashboard not loading',
    description: 'Customer reports blank screen when accessing dashboard.',
    status: 'in-progress',
    priority: 'high',
    category: 'technical',
    contactId: 'contact-1',
    contact: contacts[0],
    assignedTo: 'user-4',
    createdAt: '2024-03-09T10:00:00Z',
    updatedAt: '2024-03-10T09:00:00Z',
    messages: ticketMessages,
  },
  {
    id: 'ticket-2',
    subject: 'Invoice discrepancy',
    description: 'Billing amount does not match the agreed pricing.',
    status: 'open',
    priority: 'medium',
    category: 'billing',
    contactId: 'contact-2',
    contact: contacts[1],
    assignedTo: 'user-4',
    createdAt: '2024-03-08T14:00:00Z',
    updatedAt: '2024-03-08T14:00:00Z',
    messages: [],
  },
  {
    id: 'ticket-3',
    subject: 'Feature request: Dark mode',
    description: 'Would like to have a dark mode option for the application.',
    status: 'waiting',
    priority: 'low',
    category: 'feature-request',
    contactId: 'contact-3',
    contact: contacts[2],
    assignedTo: 'user-4',
    createdAt: '2024-03-07T09:00:00Z',
    updatedAt: '2024-03-09T16:00:00Z',
    messages: [],
  },
  {
    id: 'ticket-4',
    subject: 'Cannot export reports',
    description: 'Export button does not work. Getting error message.',
    status: 'resolved',
    priority: 'high',
    category: 'bug',
    contactId: 'contact-4',
    contact: contacts[3],
    assignedTo: 'user-4',
    createdAt: '2024-03-05T11:00:00Z',
    updatedAt: '2024-03-08T10:00:00Z',
    resolvedAt: '2024-03-08T10:00:00Z',
    messages: [],
  },
  {
    id: 'ticket-5',
    subject: 'How to add team members?',
    description: 'Need help understanding user management.',
    status: 'closed',
    priority: 'low',
    category: 'general',
    contactId: 'contact-5',
    contact: contacts[4],
    assignedTo: 'user-4',
    createdAt: '2024-03-04T15:00:00Z',
    updatedAt: '2024-03-05T09:00:00Z',
    resolvedAt: '2024-03-05T09:00:00Z',
    messages: [],
  },
  {
    id: 'ticket-6',
    subject: 'API integration issues',
    description: 'Getting 401 errors when calling the REST API.',
    status: 'in-progress',
    priority: 'urgent',
    category: 'technical',
    contactId: 'contact-6',
    contact: contacts[5],
    assignedTo: 'user-4',
    createdAt: '2024-03-10T08:00:00Z',
    updatedAt: '2024-03-10T10:00:00Z',
    messages: [],
  },
]

// Tasks
export const tasks: Task[] = [
  {
    id: 'task-1',
    title: 'Follow up with TechCorp on contract',
    description: 'Send revised contract with updated pricing.',
    dueDate: '2024-03-12T00:00:00Z',
    priority: 'high',
    status: 'pending',
    relatedTo: { type: 'deal', id: 'deal-1', name: 'TechCorp Enterprise License' },
    assignedTo: 'user-1',
    createdAt: '2024-03-09T10:00:00Z',
  },
  {
    id: 'task-2',
    title: 'Prepare demo for Global Inc',
    description: 'Customize demo to showcase process automation features.',
    dueDate: '2024-03-14T00:00:00Z',
    priority: 'high',
    status: 'in-progress',
    relatedTo: { type: 'deal', id: 'deal-2', name: 'Global Inc Process Automation' },
    assignedTo: 'user-2',
    createdAt: '2024-03-08T11:00:00Z',
  },
  {
    id: 'task-3',
    title: 'Review FinancePlus security requirements',
    description: 'Go through the security questionnaire and prepare responses.',
    dueDate: '2024-03-11T00:00:00Z',
    priority: 'medium',
    status: 'pending',
    relatedTo: { type: 'deal', id: 'deal-5', name: 'FinancePlus Compliance Package' },
    assignedTo: 'user-1',
    createdAt: '2024-03-07T14:00:00Z',
  },
  {
    id: 'task-4',
    title: 'Call new lead Amanda Foster',
    description: 'Initial discovery call with CloudServe.',
    dueDate: '2024-03-11T00:00:00Z',
    priority: 'high',
    status: 'pending',
    relatedTo: { type: 'lead', id: 'lead-3', name: 'Amanda Foster - CloudServe' },
    assignedTo: 'user-2',
    createdAt: '2024-03-08T14:30:00Z',
  },
  {
    id: 'task-5',
    title: 'Send HIPAA documentation',
    description: 'Compile and send HIPAA compliance documentation.',
    dueDate: '2024-03-15T00:00:00Z',
    priority: 'medium',
    status: 'pending',
    relatedTo: { type: 'contact', id: 'contact-6', name: 'Maria Rodriguez' },
    assignedTo: 'user-3',
    createdAt: '2024-03-06T16:00:00Z',
  },
  {
    id: 'task-6',
    title: 'Weekly team meeting',
    description: 'Review pipeline and discuss blockers.',
    dueDate: '2024-03-11T10:00:00Z',
    priority: 'low',
    status: 'pending',
    assignedTo: 'user-1',
    createdAt: '2024-03-04T09:00:00Z',
  },
  {
    id: 'task-7',
    title: 'Update CRM documentation',
    description: 'Add new feature documentation to help center.',
    dueDate: '2024-03-18T00:00:00Z',
    priority: 'low',
    status: 'pending',
    assignedTo: 'user-4',
    createdAt: '2024-03-09T11:00:00Z',
  },
]

// Calendar Events
export const calendarEvents: CalendarEvent[] = [
  {
    id: 'event-1',
    title: 'TechCorp Contract Review',
    description: 'Review and finalize contract terms with legal.',
    start: '2024-03-11T10:00:00Z',
    end: '2024-03-11T11:00:00Z',
    type: 'meeting',
    attendees: ['user-1', 'user-5'],
    relatedTo: { type: 'deal', id: 'deal-1' },
  },
  {
    id: 'event-2',
    title: 'Global Inc Demo',
    description: 'Product demonstration for Global Inc team.',
    start: '2024-03-12T14:00:00Z',
    end: '2024-03-12T15:30:00Z',
    type: 'meeting',
    attendees: ['user-2', 'user-1'],
    relatedTo: { type: 'deal', id: 'deal-2' },
  },
  {
    id: 'event-3',
    title: 'Call with CloudServe',
    description: 'Discovery call with Amanda Foster.',
    start: '2024-03-11T15:00:00Z',
    end: '2024-03-11T15:30:00Z',
    type: 'call',
    attendees: ['user-2'],
    relatedTo: { type: 'lead', id: 'lead-3' },
  },
  {
    id: 'event-4',
    title: 'Weekly Sales Standup',
    description: 'Weekly team sync and pipeline review.',
    start: '2024-03-11T09:00:00Z',
    end: '2024-03-11T09:30:00Z',
    type: 'meeting',
    attendees: ['user-1', 'user-2', 'user-3', 'user-5'],
  },
  {
    id: 'event-5',
    title: 'FinancePlus Follow-up',
    description: 'Discuss security requirements and timeline.',
    start: '2024-03-13T11:00:00Z',
    end: '2024-03-13T12:00:00Z',
    type: 'call',
    attendees: ['user-1'],
    relatedTo: { type: 'deal', id: 'deal-5' },
  },
  {
    id: 'event-6',
    title: 'Q1 Review Meeting',
    description: 'Quarterly review with management.',
    start: '2024-03-15T14:00:00Z',
    end: '2024-03-15T16:00:00Z',
    type: 'meeting',
    attendees: ['user-1', 'user-2', 'user-3', 'user-4', 'user-5'],
  },
]

// Notifications
export const notifications: Notification[] = [
  {
    id: 'notif-1',
    title: 'New lead assigned',
    message: 'Nancy Davis from Davis & Associates Law has been assigned to you.',
    type: 'info',
    read: false,
    createdAt: '2024-03-10T09:30:00Z',
    link: '/leads',
  },
  {
    id: 'notif-2',
    title: 'Deal moved to negotiation',
    message: 'TechCorp Enterprise License has moved to negotiation stage.',
    type: 'success',
    read: false,
    createdAt: '2024-03-10T08:00:00Z',
    link: '/deals',
  },
  {
    id: 'notif-3',
    title: 'Urgent ticket assigned',
    message: 'API integration issues ticket from HealthCare Solutions.',
    type: 'warning',
    read: false,
    createdAt: '2024-03-10T08:15:00Z',
    link: '/tickets',
  },
  {
    id: 'notif-4',
    title: 'Task due today',
    message: 'Follow up with TechCorp on contract is due today.',
    type: 'warning',
    read: true,
    createdAt: '2024-03-10T07:00:00Z',
    link: '/tasks',
  },
  {
    id: 'notif-5',
    title: 'Deal won!',
    message: 'EduLearn Non-Profit License has been closed successfully.',
    type: 'success',
    read: true,
    createdAt: '2024-03-01T12:00:00Z',
    link: '/deals',
  },
]

// AI Insights
export const aiInsights: AIInsight[] = [
  {
    id: 'insight-1',
    type: 'deal-prediction',
    title: 'High win probability',
    description: 'FinancePlus deal has 85% chance of closing based on engagement patterns and deal velocity.',
    confidence: 85,
    relatedTo: { type: 'deal', id: 'deal-5', name: 'FinancePlus Compliance Package' },
    suggestedAction: 'Schedule final pricing discussion this week.',
    createdAt: '2024-03-10T06:00:00Z',
  },
  {
    id: 'insight-2',
    type: 'lead-score',
    title: 'Hot lead detected',
    description: 'Sophie Chen shows high engagement with score of 92. Multiple website visits and email opens.',
    confidence: 92,
    relatedTo: { type: 'lead', id: 'lead-1', name: 'Sophie Chen - InnovateAI' },
    suggestedAction: 'Prioritize outreach within 24 hours.',
    createdAt: '2024-03-10T06:00:00Z',
  },
  {
    id: 'insight-3',
    type: 'churn-risk',
    title: 'Potential churn risk',
    description: 'RetailMax has not logged in for 14 days. Historical pattern suggests churn risk.',
    confidence: 68,
    relatedTo: { type: 'contact', id: 'contact-4', name: 'Lisa Anderson - RetailMax' },
    suggestedAction: 'Schedule a check-in call to address concerns.',
    createdAt: '2024-03-09T06:00:00Z',
  },
  {
    id: 'insight-4',
    type: 'recommendation',
    title: 'Upsell opportunity',
    description: 'TechCorp usage patterns indicate need for additional user licenses.',
    confidence: 78,
    relatedTo: { type: 'contact', id: 'contact-1', name: 'John Smith - TechCorp' },
    suggestedAction: 'Discuss enterprise expansion during contract renewal.',
    createdAt: '2024-03-08T06:00:00Z',
  },
  {
    id: 'insight-5',
    type: 'deal-prediction',
    title: 'At-risk deal',
    description: 'StartupXYZ deal has gone cold. No activity in 7 days.',
    confidence: 42,
    relatedTo: { type: 'deal', id: 'deal-3', name: 'StartupXYZ Growth Plan' },
    suggestedAction: 'Re-engage with special offer or extended trial.',
    createdAt: '2024-03-10T06:00:00Z',
  },
]

// Dashboard Stats
export const dashboardStats: DashboardStats = {
  totalRevenue: 784000,
  revenueChange: 12.5,
  totalDeals: 9,
  dealsChange: 8,
  newLeads: 8,
  leadsChange: 15,
  openTickets: 4,
  ticketsChange: -10,
  conversionRate: 32,
  conversionChange: 5,
  avgDealSize: 87111,
  avgDealSizeChange: 3.2,
}

// Chart Data
export const revenueChartData = [
  { month: 'Jan', revenue: 45000, deals: 3 },
  { month: 'Feb', revenue: 52000, deals: 4 },
  { month: 'Mar', revenue: 61000, deals: 5 },
  { month: 'Apr', revenue: 58000, deals: 4 },
  { month: 'May', revenue: 72000, deals: 6 },
  { month: 'Jun', revenue: 68000, deals: 5 },
  { month: 'Jul', revenue: 85000, deals: 7 },
  { month: 'Aug', revenue: 92000, deals: 8 },
  { month: 'Sep', revenue: 78000, deals: 6 },
  { month: 'Oct', revenue: 95000, deals: 8 },
  { month: 'Nov', revenue: 88000, deals: 7 },
  { month: 'Dec', revenue: 105000, deals: 9 },
]

export const pipelineChartData = [
  { stage: 'Lead', value: 75000, count: 1 },
  { stage: 'Qualified', value: 119000, count: 2 },
  { stage: 'Proposal', value: 205000, count: 2 },
  { stage: 'Negotiation', value: 350000, count: 2 },
  { stage: 'Closed Won', value: 35000, count: 1 },
]

export const leadSourceChartData = [
  { source: 'Website', value: 35, fill: 'var(--chart-1)' },
  { source: 'Referral', value: 28, fill: 'var(--chart-2)' },
  { source: 'LinkedIn', value: 20, fill: 'var(--chart-3)' },
  { source: 'Events', value: 12, fill: 'var(--chart-4)' },
  { source: 'Other', value: 5, fill: 'var(--chart-5)' },
]

export const activityChartData = [
  { day: 'Mon', calls: 12, emails: 25, meetings: 3 },
  { day: 'Tue', calls: 15, emails: 30, meetings: 5 },
  { day: 'Wed', calls: 8, emails: 22, meetings: 4 },
  { day: 'Thu', calls: 18, emails: 35, meetings: 6 },
  { day: 'Fri', calls: 10, emails: 28, meetings: 2 },
]
